// Bakes the Kotlin project's migration SQL into a Dart source file.
//
// The core package must stay asset-free so that `dart test` works with no
// bundling step and the same code runs in a Flutter app, a CLI and a future
// sync isolate. Rather than teach it to load assets, the SQL is embedded.
//
// Usage: dart tool/generate_migrations.dart
import 'dart:io';

void main() {
  final repoRoot = Directory.current.parent.path;
  final source = Directory('$repoRoot/uhabits-core/assets/main/migrations');
  if (!source.existsSync()) {
    stderr.writeln('Migration assets not found at ${source.path}');
    exit(2);
  }

  final files = source
      .listSync()
      .whereType<File>()
      .where((f) => f.path.endsWith('.sql'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  final buffer = StringBuffer()
    ..writeln('// GENERATED by tool/generate_migrations.dart — do not edit by hand.')
    ..writeln('//')
    ..writeln('// Verbatim copies of uhabits-core/assets/main/migrations/*.sql, the same')
    ..writeln('// scripts the Kotlin app applies. A fresh database stamps user_version = 8')
    ..writeln('// and migrates up, so migration 09 is the effective CREATE TABLE script.')
    ..writeln('library;')
    ..writeln()
    ..writeln('/// Migration SQL keyed by schema version.')
    ..writeln('const Map<int, String> migrationSql = {');

  for (final file in files) {
    final version = int.parse(file.uri.pathSegments.last.split('.').first);
    final sql = file.readAsStringSync();
    buffer
      ..writeln('  $version: r"""')
      ..write(sql)
      ..writeln('""",');
  }

  buffer
    ..writeln('};')
    ..writeln()
    ..writeln('/// Highest schema version shipped. Matches Constants.DATABASE_VERSION.')
    ..writeln('const int databaseVersion = ${files.map((f) => int.parse(f.uri.pathSegments.last.split('.').first)).reduce((a, b) => a > b ? a : b)};')
    ..writeln()
    ..writeln("/// Database file name. Matches Constants.DATABASE_FILENAME.")
    ..writeln("const String databaseFilename = 'uhabits.db';");

  final out = File('$repoRoot/uhabits-flutter/packages/uhabits_core/lib/src/database/migrations.g.dart');
  out.parent.createSync(recursive: true);
  out.writeAsStringSync(buffer.toString());
  stdout.writeln('Wrote ${out.path} with ${files.length} migrations');
}
