/// Migrations for what the original does not have.
///
/// `migrations.g.dart` is generated by `tool/generate_migrations.dart` from the
/// Kotlin assets and says so at the top: anything written into it is lost on
/// the next run. Extension schema therefore lives here, by hand.
///
/// Numbering starts at [firstExtensionVersion] rather than at 26 so that the
/// original could ship several more migrations without ever colliding.
library;

import 'migrations.g.dart';

/// The first schema version that belongs to this port rather than to Kotlin.
const int firstExtensionVersion = 100;

/// Whether [version] is one of ours.
///
/// The boundary is stated once, here, because more than one caller has to
/// decide where to look for a script and they must not disagree.
bool isExtensionVersion(int version) => version >= firstExtensionVersion;

const Map<int, String> extensionMigrationSql = <int, String>{
  100: r"""
create table SleepSessions (
    id integer primary key autoincrement,
    habit integer not null references Habits(id) on delete cascade,
    day integer not null,
    bed_start integer not null,
    wake_end integer not null,
    asleep_minutes integer not null,
    derived_from_asleep integer not null,
    utc_offset integer not null,
    source integer not null,
    source_id text,
    updated_at integer not null
);

create unique index idx_sleep_sessions_habit_day
    on SleepSessions(habit, day);

create table SleepGoals (
    habit integer primary key references Habits(id) on delete cascade,
    bed_minutes integer not null,
    wake_minutes integer not null,
    min_sleep_minutes integer not null,
    weight_sleep real not null,
    weight_bed real not null,
    weight_wake real not null,
    half_credit_time_minutes integer not null,
    half_credit_sleep_minutes integer not null,
    home_utc_offset integer not null,
    adaptation_minutes_per_day integer not null,
    merge_gap_minutes integer not null,
    prompt_after_wake_minutes integer not null
);""",
  101: r"""
alter table SleepGoals add column covered_from_day integer;""",
  102: r"""
create table HabitDefinitions (
    habit integer primary key references Habits(id) on delete cascade,
    kind text not null,
    committed_from integer,
    payload text not null
);

insert into HabitDefinitions (habit, kind, payload)
    select habit, 'sleep', '{}' from SleepGoals;""",
};

/// The schema version this build ships.
///
/// Deliberately distinct from [databaseVersion], which is the last version the
/// Kotlin original defined and is generated from its assets. Everything that
/// asks "is this file newer than we understand" or "bring this file up to
/// date" means this one; anything still asking [databaseVersion] would refuse
/// our own database.
const int appDatabaseVersion = 102;

/// Whether a database at [version] is one this build can bring up to date.
///
/// True for the Kotlin range, which the shipped migrations climb, and for the
/// extension versions this build knows. False for the gap between them:
/// nothing that exists ever wrote a version in there, so a file carrying one
/// came from a build whose schema is unknown, and stamping it forward would be
/// a guess dressed up as an upgrade.
bool isKnownDatabaseVersion(int version) =>
    version <= databaseVersion ||
    (isExtensionVersion(version) && version <= appDatabaseVersion);

/// Whether the Kotlin original defined a script for [version].
///
/// The one caller that reads migrations from bundled asset files — the Loop
/// backup importer, which does so because upstream does — uses this to know
/// which versions those files exist for. Everything else comes from
/// [migrationSqlFor].
bool isKotlinMigration(int version) => migrationSql.containsKey(version);

/// The migration script for [version], or null when this build has none.
///
/// Versions between the last Kotlin migration and [firstExtensionVersion] are
/// deliberately absent: the gap is empty, not missing.
String? migrationSqlFor(int version) => isExtensionVersion(version)
    ? extensionMigrationSql[version]
    : migrationSql[version];
