/// Raw SQLite access to the `Habits` table.
///
/// Ported line by line from
/// `uhabits-core/src/commonMain/kotlin/org/isoron/uhabits/core/database/HabitRepository.kt`.
///
/// The SQL strings are byte-identical to the Kotlin raw strings, indentation
/// included, so the two files can be diffed side by side.
library;

import 'database.dart';

/// One row of the `Habits` table.
///
/// Kotlin declares this as a `data class` with `var` properties; Dart has no
/// data classes, so this is a plain mutable class with the same defaults. No
/// `==`/`hashCode` is generated: nothing in the port relies on structural
/// equality of rows.
class HabitData {
  HabitData({
    this.id,
    this.name = '',
    this.description = '',
    this.question = '',
    this.freqNum = 1,
    this.freqDen = 1,
    this.color = 0,
    this.position = 0,
    this.reminderHour,
    this.reminderMin,
    this.reminderDays = 0,
    this.highlight = 0,
    this.archived = 0,
    this.type = 0,
    this.targetValue = 0.0,
    this.targetType = 0,
    this.unit = '',
    this.uuid,
  });

  /// Kotlin `Long?`; Dart ints are 64-bit, so `int?` is the same thing.
  int? id;
  String name;
  String description;
  String question;
  int freqNum;
  int freqDen;
  int color;
  int position;
  int? reminderHour;
  int? reminderMin;
  int reminderDays;
  int highlight;
  int archived;
  int type;
  double targetValue;
  int targetType;
  String unit;
  String? uuid;
}

/// Reads and writes [HabitData] rows.
///
/// Every statement is prepared once, lazily (Kotlin `by lazy`, Dart
/// `late final`), cached for the lifetime of the repository, and `reset()`
/// before each use.
class HabitRepository {
  HabitRepository(this.db);

  final Database db;

  late final PreparedStatement findAllStmt = db.prepareStatement(
      """SELECT id, name, description, question, freq_num, freq_den, color,
               position, reminder_hour, reminder_min, reminder_days, highlight,
               archived, type, target_value, target_type, unit, uuid
               FROM Habits ORDER BY position""");

  late final PreparedStatement insertStmt = db.prepareStatement(
      """INSERT INTO Habits(name, description, question, freq_num, freq_den,
               color, position, reminder_hour, reminder_min, reminder_days,
               highlight, archived, type, target_value, target_type, unit, uuid)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""");

  late final PreparedStatement insertWithIdStmt = db.prepareStatement(
      """INSERT INTO Habits(id, name, description, question, freq_num, freq_den,
               color, position, reminder_hour, reminder_min, reminder_days,
               highlight, archived, type, target_value, target_type, unit, uuid)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""");

  late final PreparedStatement updateStmt = db.prepareStatement(
      """UPDATE Habits SET name=?, description=?, question=?, freq_num=?,
               freq_den=?, color=?, position=?, reminder_hour=?, reminder_min=?,
               reminder_days=?, highlight=?, archived=?, type=?, target_value=?,
               target_type=?, unit=?, uuid=? WHERE id=?""");

  late final PreparedStatement deleteStmt =
      db.prepareStatement('DELETE FROM Habits WHERE id = ?');

  List<HabitData> findAll() {
    findAllStmt.reset();
    final results = <HabitData>[];
    while (findAllStmt.step() == StepResult.row) {
      results.add(_readRow(findAllStmt));
    }
    return results;
  }

  /// Inserts [data] and returns its id.
  ///
  /// When `data.id` is null the row id is generated by SQLite and read back
  /// with `SELECT last_insert_rowid()`; when it is set, that id is written
  /// explicitly and returned as is.
  int insert(HabitData data) {
    if (data.id != null) {
      insertWithIdStmt.reset();
      insertWithIdStmt.bindLong(1, data.id!);
      _bindForInsert(insertWithIdStmt, data, offset: 1);
      insertWithIdStmt.step();
      return data.id!;
    }
    insertStmt.reset();
    _bindForInsert(insertStmt, data);
    insertStmt.step();
    return db.queryLong('SELECT last_insert_rowid()');
  }

  /// Rewrites every column of the row with id `data.id`.
  ///
  /// Throws (Kotlin: NullPointerException, Dart: TypeError) when `data.id` is
  /// null, after the other 17 parameters have already been bound.
  void update(HabitData data) {
    updateStmt.reset();
    _bindForInsert(updateStmt, data);
    updateStmt.bindLong(18, data.id!);
    updateStmt.step();
  }

  /// Deletes the `Habits` row only. The habit's `Repetitions` rows are left
  /// behind; callers (SQLiteHabitList) clear the entry list first.
  void delete(int id) {
    deleteStmt.reset();
    deleteStmt.bindLong(1, id);
    deleteStmt.step();
  }

  /// The escape hatch SQLiteHabitList uses for bulk position shifts and bulk
  /// deletes. Kotlin declares two overloads, `execSQL(sql)` and
  /// `execSQL(sql) { bind }`; Dart expresses both with one optional argument.
  void execSQL(String sql, [void Function(PreparedStatement stmt)? bind]) =>
      db.run(sql, bind);

  void _bindForInsert(PreparedStatement stmt, HabitData data,
      {int offset = 0}) {
    final o = offset;
    stmt.bindText(1 + o, data.name);
    stmt.bindText(2 + o, data.description);
    stmt.bindText(3 + o, data.question);
    stmt.bindInt(4 + o, data.freqNum);
    stmt.bindInt(5 + o, data.freqDen);
    stmt.bindInt(6 + o, data.color);
    stmt.bindInt(7 + o, data.position);
    if (data.reminderHour != null) {
      stmt.bindInt(8 + o, data.reminderHour!);
    } else {
      stmt.bindNull(8 + o);
    }
    if (data.reminderMin != null) {
      stmt.bindInt(9 + o, data.reminderMin!);
    } else {
      stmt.bindNull(9 + o);
    }
    stmt.bindInt(10 + o, data.reminderDays);
    stmt.bindInt(11 + o, data.highlight);
    stmt.bindInt(12 + o, data.archived);
    stmt.bindInt(13 + o, data.type);
    stmt.bindReal(14 + o, data.targetValue);
    stmt.bindInt(15 + o, data.targetType);
    stmt.bindText(16 + o, data.unit);
    if (data.uuid != null) {
      stmt.bindText(17 + o, data.uuid!);
    } else {
      stmt.bindNull(17 + o);
    }
  }

  HabitData _readRow(PreparedStatement stmt) {
    return HabitData(
      id: stmt.getLong(0),
      name: stmt.getText(1),
      description: stmt.getText(2),
      question: stmt.getText(3),
      freqNum: stmt.getInt(4),
      freqDen: stmt.getInt(5),
      color: stmt.getInt(6),
      position: stmt.getInt(7),
      reminderHour: stmt.getIntOrNull(8),
      reminderMin: stmt.getIntOrNull(9),
      reminderDays: stmt.getInt(10),
      highlight: stmt.getInt(11),
      archived: stmt.getInt(12),
      type: stmt.getInt(13),
      targetValue: stmt.getReal(14),
      targetType: stmt.getInt(15),
      unit: stmt.getText(16),
      uuid: stmt.getTextOrNull(17),
    );
  }
}
