// GENERATED by tool/generate_migrations.dart — do not edit by hand.
//
// Verbatim copies of uhabits-core/assets/main/migrations/*.sql, the same
// scripts the Kotlin app applies. A fresh database stamps user_version = 8
// and migrates up, so migration 09 is the effective CREATE TABLE script.
library;

/// Migration SQL keyed by schema version.
const Map<int, String> migrationSql = {
  9: r"""
create table Habits (
    id integer primary key autoincrement,
    archived integer,
    color integer,
    description text,
    freq_den integer,
    freq_num integer,
    highlight integer,
    name text,
    position integer,
    reminder_hour integer,
    reminder_min integer
);

create table Checkmarks (
    id integer primary key autoincrement,
    habit integer references habits(id),
    timestamp integer,
    value integer
);

create table Repetitions (
    id integer primary key autoincrement,
    habit integer references habits(id),
    timestamp integer
);

create table Streak (
    id integer primary key autoincrement,
    end integer,
    habit integer references habits(id),
    length integer,
    start integer
);

create table Score (
    id integer primary key autoincrement,
    habit integer references habits(id),
    score integer,
    timestamp integer
);
""",
  10: r"""
delete from Score;
delete from Streak;
delete from Checkmarks;""",
  11: r"""
alter table Habits add column reminder_days integer not null default 127;""",
  12: r"""
delete from Score;
delete from Streak;
delete from Checkmarks;""",
  13: r"""
create index idx_score_habit_timestamp on Score(habit, timestamp);
create index idx_checkmark_habit_timestamp on Checkmarks(habit, timestamp);
create index idx_repetitions_habit_timestamp on Repetitions(habit, timestamp);
create index idx_streak_habit_end on Streak(habit, end);""",
  14: r"""
update habits set color=0 where color=-2937041;
update habits set color=1 where color=-1684967;
update habits set color=2 where color=-415707;
update habits set color=3 where color=-5262293;
update habits set color=4 where color=-13070788;
update habits set color=5 where color=-16742021;
update habits set color=6 where color=-16732991;
update habits set color=7 where color=-16540699;
update habits set color=8 where color=-10603087;
update habits set color=9 where color=-7461718;
update habits set color=10 where color=-2614432;
update habits set color=11 where color=-13619152;
update habits set color=12 where color=-5592406;
update habits set color=0 where color<0 or color>12;""",
  15: r"""
delete from Score;
delete from Streak;
delete from Checkmarks;""",
  16: r"""
alter table Habits add column type integer not null default 0;
alter table Repetitions add column value integer not null default 2;""",
  17: r"""
drop table Score;
create table Score (
    id integer primary key autoincrement,
    habit integer references habits(id),
    score real,
    timestamp integer);

create index idx_score_habit_timestamp on Score(habit, timestamp);

delete from streak;
delete from checkmarks;""",
  18: r"""
alter table Habits add column target_type integer not null default 0;
alter table Habits add column target_value real not null default 0;
alter table Habits add column unit text not null default '';""",
  19: r"""
create table Events (
    id integer primary key autoincrement,
    timestamp integer,
    message text,
    server_id integer
);""",
  20: r"""
drop table checkmarks;
drop table streak;
drop table score;
""",
  21: r"""
update habits set color=19 where color=12;
update habits set color=17 where color=11;
update habits set color=15 where color=10;
update habits set color=14 where color=9;
update habits set color=13 where color=8;
update habits set color=10 where color=7;
update habits set color=9 where color=6;
update habits set color=8 where color=5;
update habits set color=7 where color=4;
update habits set color=5 where color=3;
update habits set color=4 where color=2;
update habits set color=0 where color<0 or color>19;""",
  22: r"""
delete from repetitions where habit not in (select id from habits);
delete from repetitions where timestamp is null;
delete from repetitions where habit is null;
delete from repetitions where rowid not in (
    select min(rowid) from repetitions group by habit, timestamp
);

begin transaction;

    alter table Repetitions rename to RepetitionsBak;
    create table Repetitions (
        id integer primary key autoincrement,
        habit integer not null references habits(id),
        timestamp integer not null,
        value integer not null);
    drop index if exists idx_repetitions_habit_timestamp;
    create unique index idx_repetitions_habit_timestamp on Repetitions(
        habit, timestamp);
    insert into Repetitions select * from RepetitionsBak;
    drop table RepetitionsBak;

commit;

pragma foreign_keys=ON;""",
  23: r"""
alter table Habits add column question text;

update Habits set question = description;

update Habits set description = '';""",
  24: r"""
alter table habits add column uuid text;
update habits set uuid = lower(hex(randomblob(16) || id));""",
  25: r"""
alter table Repetitions add column notes text;""",
};

/// Highest schema version shipped. Matches Constants.DATABASE_VERSION.
const int databaseVersion = 25;

/// Database file name. Matches Constants.DATABASE_FILENAME.
const String databaseFilename = 'uhabits.db';
