/// Port of
/// uhabits-android/src/main/java/org/isoron/uhabits/activities/habits/list/views/HabitCardListController.kt
///
/// The class lives in the Android source set upstream, but nothing in it is
/// Android: it is a two-state machine over the selection held by
/// [HabitCardListAdapter], driven by four gestures and reporting to two
/// collaborators — [ListHabitsBehavior] for the "open this habit" and "reorder
/// these habits" intents, and the contextual action bar for start / change /
/// finish.
///
/// What was left behind:
///
///  * `androidx.appcompat.view.ActionMode` and the `ListHabitsSelectionMenu`
///    that implements its callback. Only the three calls the controller makes
///    into it survive, as [HabitCardListSelectionMenu]; the menu's inflation,
///    its item visibility and the `activeActionMode.title` assignment are the
///    widget layer's business.
///  * `HabitCardListView` itself. Its nested `Controller` interface, which is
///    all the controller implements, is ported as
///    [HabitCardListViewController].
library;

import '../../../../models/habit.dart';
import '../../../../models/model_observable.dart';
import 'habit_card_list_adapter.dart';
import 'list_habits_behavior.dart';

/// Port of the nested `HabitCardListView.Controller` interface.
///
/// Every method has an empty body in Kotlin, so it is ported as a concrete
/// class to be extended rather than an interface to be implemented — the same
/// shape [HabitCardListCacheListener] already has.
/// Kotlin names the two click parameters `pos` and the drag one `position`,
/// while the overrides in the controller name all three `position`; the port
/// uses `position` throughout.
class HabitCardListViewController {
  void drop(int from, int to) {}

  void onItemClick(int position) {}

  void onItemLongClick(int position) {}

  void startDrag(int position) {}
}

/// The slice of `ListHabitsSelectionMenu` the controller can see.
///
/// Upstream this is an `ActionMode.Callback` that starts, invalidates and
/// finishes an Android contextual action bar. What crosses into core is only
/// the three-signal protocol: selection started, selection changed, selection
/// finished. The widget layer decides what the bar looks like — including its
/// title, which upstream sets to `listAdapter.selected.size.toString()`.
abstract interface class HabitCardListSelectionMenu {
  /// The first habit was just selected: show the contextual bar.
  void onSelectionStart();

  /// The selection changed but is still non-empty: the bar must redraw its
  /// title and recompute which items are visible.
  void onSelectionChange();

  /// Nothing is selected any more: dismiss the bar.
  void onSelectionFinish();
}

/// Kotlin injects the selection menu as `Lazy<ListHabitsSelectionMenu>`,
/// because the menu holds a `Lazy<HabitCardListController>` right back: the two
/// are mutually dependent and one of the two edges has to be deferred.
///
/// A Dart closure is the same deferral. It is expected to return the same
/// instance on every call, as `Lazy.value` does.
typedef LazyHabitCardListSelectionMenu = HabitCardListSelectionMenu Function();

/// A Mode describes the behavior of the list upon clicking, long clicking and
/// dragging an item. This depends on whether some items are already selected or
/// not.
///
/// Kotlin declares it `private interface Mode` and the two implementations
/// `internal inner class`; Dart has neither nesting nor `internal`, so all
/// three are top-level. The two classes take the controller where Kotlin's
/// inner classes capture the outer `this`.
abstract interface class HabitCardListControllerMode {
  void onItemClick(int position);

  bool onItemLongClick(int position);

  void startDrag(int position);
}

/// Controller responsible for receiving and processing the events generated by
/// a habit list view. These include selecting and reordering items, toggling
/// checkmarks and clicking habits.
class HabitCardListController extends HabitCardListViewController
    implements ModelObservableListener {
  HabitCardListController(this._adapter, this._behavior, this._selectionMenu) {
    _activeMode = NormalMode(this);
    _adapter.observable.addListener(this);
  }

  final HabitCardListAdapter _adapter;

  final ListHabitsBehavior _behavior;

  final LazyHabitCardListSelectionMenu _selectionMenu;

  late HabitCardListControllerMode _activeMode;

  /// Which of the two modes is active. Kotlin keeps `activeMode` private and
  /// has no test for it; it is readable here so the state machine can be
  /// asserted.
  HabitCardListControllerMode get activeMode => _activeMode;

  @override
  void drop(int from, int to) {
    if (from == to) return;
    _cancelSelection();

    final habitFrom = _adapter.getItem(from);
    final habitTo = _adapter.getItem(to);
    if (habitFrom == null || habitTo == null) return;

    _adapter.performReorder(from, to);
    _behavior.onReorderHabit(habitFrom, habitTo);
  }

  @override
  void onItemClick(int position) {
    _activeMode.onItemClick(position);
  }

  @override
  void onItemLongClick(int position) {
    _activeMode.onItemLongClick(position);
  }

  /// The adapter's [ModelObservable] fires on every cache callback and on
  /// [HabitCardListAdapter.clearSelection]. An empty selection means whatever
  /// the contextual bar was showing is gone.
  @override
  void onModelChange() {
    if (_adapter.isSelectionEmpty) {
      _activeMode = NormalMode(this);
      _selectionMenu().onSelectionFinish();
    }
  }

  /// Called by the selection menu when its action mode is destroyed — the
  /// system back button, a tap outside, or the bar's own close button.
  void onSelectionFinished() {
    _cancelSelection();
  }

  @override
  void startDrag(int position) {
    _activeMode.startDrag(position);
  }

  /// Toggles one row and then re-derives the mode from the selection.
  ///
  /// This is the only place the mode is computed from the selection; callers
  /// that force a mode afterwards (see [NormalMode.startSelection]) override
  /// this decision.
  void _toggleSelection(int position) {
    _adapter.toggleSelection(position);
    _activeMode =
        _adapter.isSelectionEmpty ? NormalMode(this) : SelectionMode(this);
  }

  /// Drops the selection and dismisses the bar.
  ///
  /// [HabitCardListAdapter.clearSelection] notifies the ModelObservable, which
  /// re-enters this object through [onModelChange] and already resets the mode
  /// and finishes the bar — so a non-empty selection makes
  /// `onSelectionFinish()` fire twice. Upstream behaviour, kept.
  void _cancelSelection() {
    _adapter.clearSelection();
    _activeMode = NormalMode(this);
    _selectionMenu().onSelectionFinish();
  }
}

/// Port of the nested `HabitCardListController.HabitListener` interface.
///
/// Declared upstream and never implemented or referenced by anything — the
/// controller talks to [ListHabitsBehavior] directly. Ported so the file stays
/// a complete image of the original.
abstract interface class HabitCardListControllerHabitListener {
  void onHabitClick(Habit habit);

  void onHabitReorder(Habit from, Habit to);
}

/// Mode activated when there are no items selected. Clicks trigger habit click.
/// Long clicks start selection.
class NormalMode implements HabitCardListControllerMode {
  NormalMode(this._controller);

  final HabitCardListController _controller;

  @override
  void onItemClick(int position) {
    final habit = _controller._adapter.getItem(position);
    if (habit == null) return;
    _controller._behavior.onClickHabit(habit);
  }

  @override
  bool onItemLongClick(int position) {
    startSelection(position);
    return true;
  }

  @override
  void startDrag(int position) {
    startSelection(position);
  }

  /// Note the unconditional `activeMode = SelectionMode()`: a long press on a
  /// position with no habit behind it toggles nothing, so
  /// [HabitCardListController._toggleSelection] leaves NormalMode in place —
  /// and this line then overrides it and starts a contextual action bar over an
  /// empty selection. Upstream bug, reproduced.
  void startSelection(int position) {
    _controller._toggleSelection(position);
    _controller._activeMode = SelectionMode(_controller);
    _controller._selectionMenu().onSelectionStart();
  }
}

/// Mode activated when some items are already selected. Clicks toggle item
/// selection. Long clicks select more items.
class SelectionMode implements HabitCardListControllerMode {
  SelectionMode(this._controller);

  final HabitCardListController _controller;

  @override
  void onItemClick(int position) {
    _controller._toggleSelection(position);
    notifyListener();
  }

  @override
  bool onItemLongClick(int position) {
    _controller._toggleSelection(position);
    notifyListener();
    return true;
  }

  @override
  void startDrag(int position) {
    _controller._toggleSelection(position);
    notifyListener();
  }

  /// Reads the mode [HabitCardListController._toggleSelection] just derived: a
  /// still-selected list invalidates the bar, an emptied one finishes it.
  void notifyListener() {
    if (_controller._activeMode is SelectionMode) {
      _controller._selectionMenu().onSelectionChange();
    } else {
      _controller._selectionMenu().onSelectionFinish();
    }
  }
}
